### ISSUE TITLE
0.6.6 pdfs show invalid/corrupted in firefox and foxit reader

### ISSUE THREAD

**Issue by patman023** [MarcBoule/Geodesics#6] opened 2019-02-15 22:12 UTC

**Comment by patman023** [comment] 2019-02-15 22:13
FF 65.0.1 64 bit
foxit 9.3.0.10826

**Comment by MarcBoule** [comment] 2019-02-16 00:15
Strange, I have the exact same Firefox (65.0.1 64-bit) and I can't reproduce the problem (Win10). I also tried with FF on my mac, and it looks good also. Perhaps it's a github-related problem?

**Comment by patman023** [comment] 2019-02-16 06:02
FF: 
![screenshot_2019-02-15 marcboule geodesics](https://user-images.githubusercontent.com/36520477/52895279-3c0e1000-3175-11e9-9d53-efd488b2b159.png)

If I download the file using either FF or Chrome (whihc renders on github.com ok), the local copy will not render in either browser or using Foxit.

**Comment by MarcBoule** [comment] 2019-02-16 12:41
Hmm, I'm trying the same things as you are and it looks ok. 

From github:
![image](https://user-images.githubusercontent.com/33604154/52899933-edd12f00-31bd-11e9-8862-dbb2e7034334.png)

From a local copy that I drag and drop into FF:
![image](https://user-images.githubusercontent.com/33604154/52899944-10634800-31be-11e9-9b35-cf4fcd12a5e0.png)

I'll notify Pyer and we'll keep an eye open for anything, but if none of us can repeat it, it won't be easy to debug! :-)

**Comment by patman023** [comment] 2019-02-16 14:50
Weird. Maybe I'll comb the Github support. Probably the same crap as svgs.

**Comment by MarcBoule** [comment] 2019-04-16 23:11
Since we can't reproduce this, I think I'll close the issue.

**Closed by MarcBoule** 2019-04-16 23:11 UTC

**Comment by patman023** [comment] 2019-04-17 20:33
Working on my end now. (sorry, forgot to follow-up on this)
